import 'package:drift/drift.dart';
import 'package:flutter_template/services/base/database/app_database.dart';

final localWeatherCompanion = LocalCurrentWeatherCompanion(
  base: const Value("base"),
  cloudsAll: const Value(4),
  cod: const Value(10),
  coordLat: const Value(100.45),
  coordLon: const Value(90.12),
  dt: const Value(1),
  id: const Value(1),
  mainFeelsLike: const Value(32.45),
  mainTemp: const Value(28.8),
  mainTempMin: const Value(21.45),
  mainTempMax: const Value(34),
  mainHumidity: const Value(78),
  mainPressure: const Value(100),
  name: const Value("name 1"),
  sysCountry: const Value("country 1"),
  sysSunrise: const Value(1234567),
  sysSunset: const Value(4567123),
  timezone: const Value(1),
  visibility: const Value(100),
  weatherId: const Value(1),
  weatherDescription: const Value("description"),
  weatherIcon: const Value("01d"),
  weatherMain: const Value("main"),
  windDeg: const Value(10),
  windSpeed: const Value(20),
  updatedAt: Value(DateTime(1970)),
);

final localWeatherData = LocalCurrentWeatherData(
  base: "base",
  cloudsAll: 4,
  cod: 10,
  coordLat: 100.45,
  coordLon: 90.12,
  dt: 1,
  id: 1,
  mainFeelsLike: 32.45,
  mainTemp: 28.8,
  mainTempMin: 21.45,
  mainTempMax: 34,
  mainHumidity: 78,
  mainPressure: 100,
  name: "name 1",
  sysCountry: "country 1",
  sysSunrise: 1234567,
  sysSunset: 4567123,
  timezone: 1,
  visibility: 100,
  weatherId: 1,
  weatherDescription: "description",
  weatherIcon: "01d",
  weatherMain: "main",
  windDeg: 10,
  windSpeed: 20,
  updatedAt: DateTime(1970),
);
