import 'package:flutter/material.dart';

final lightColorScheme = ColorScheme.fromSeed(
  seedColor: const Color(0xFF6750A4),
  brightness: Brightness.light,
  primary: const Color(0xFF6F33E3),
  onPrimary: const Color(0xFFFFFFFF),
  primaryContainer: const Color(0xFFEBDDFF),
  onPrimaryContainer: const Color(0xFF22005D),
  secondary: const Color(0xFF3A48E8),
  onSecondary: const Color(0xFFFFFFFF),
  secondaryContainer: const Color(0xFFDFE0FF),
  onSecondaryContainer: const Color(0xFF00006F),
  tertiary: const Color(0xFF7D5260),
  onTertiary: const Color(0xFFFFFFFF),
  tertiaryContainer: const Color(0xFFFFD8E4),
  onTertiaryContainer: const Color(0xFF31111D),
  error: const Color(0xFFB3261E),
  errorContainer: const Color(0xFFF9DEDC),
  onError: const Color(0xFFFFFFFF),
  onErrorContainer: const Color(0xFF410E0B),
  background: const Color(0xFFFFFBFE),
  onBackground: const Color(0xFF1C1B1F),
  surface: const Color(0xFFFFFBFE),
  onSurface: const Color(0xFF1C1B1F),
  surfaceVariant: const Color(0xFFE7E0EC),
  onSurfaceVariant: const Color(0xFF49454F),
  outline: const Color(0xFF79747E),
  onInverseSurface: const Color(0xFFF4EFF4),
  inverseSurface: const Color(0xFF313033),
  inversePrimary: const Color(0xFFD2BCFF),
  shadow: const Color(0xFF000000),
);

final darkColorScheme = ColorScheme.fromSeed(
  seedColor: const Color(0xFF6750A4),
  brightness: Brightness.dark,
  primary: const Color(0xFFD2BCFF),
  onPrimary: const Color(0xFF3B0093),
  primaryContainer: const Color(0xFF5600CA),
  onPrimaryContainer: const Color(0xFFEBDDFF),
  secondary: const Color(0xFFBCC2FF),
  onSecondary: const Color(0xFF0001AD),
  secondaryContainer: const Color(0xFF1827D1),
  onSecondaryContainer: const Color(0xFFDFE0FF),
  tertiary: const Color(0xFFEFB8C8),
  onTertiary: const Color(0xFF492532),
  tertiaryContainer: const Color(0xFF633B48),
  onTertiaryContainer: const Color(0xFFFFD8E4),
  error: const Color(0xFFF2B8B5),
  errorContainer: const Color(0xFF8C1D18),
  onError: const Color(0xFF601410),
  onErrorContainer: const Color(0xFFF9DEDC),
  background: const Color(0xFF1C1B1F),
  onBackground: const Color(0xFFE6E1E5),
  surface: const Color(0xFF1C1B1F),
  onSurface: const Color(0xFFE6E1E5),
  surfaceVariant: const Color(0xFF49454F),
  onSurfaceVariant: const Color(0xFFCAC4D0),
  outline: const Color(0xFF938F99),
  onInverseSurface: const Color(0xFF1C1B1F),
  inverseSurface: const Color(0xFFE6E1E5),
  inversePrimary: const Color(0xFF6F33E3),
  shadow: const Color(0xFF000000),
);
