# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

       
        Dir.chdir "../" do
 	    sh "scripts/build.sh ipa qa"
            api_key = app_store_connect_api_key(
                    key_id: "GHRQT62WNS",
                    issuer_id: "d51671fc-2feb-474b-8515-90ecbb4790ba",
                    key_filepath: "scripts/key.p8",
                  )
         upload_to_testflight(api_key: api_key, ipa: "build/ios/ipa/prod.ipa")
        end
  end
end
