#!/bin/sh

echo "Running static analysis with flutter analyze:"

melos run analyze

status=$?

if [ "$status" = 0 ] ; then
  echo "Static analysis ran successfully."
  exit 0
else
  echo "Static analysis failed. Running dart fix."
  melos run dart-fix
  echo "Static analysis failed. Running flutter format"
  melos run format
  exit 1
fi